### PR TITLE
[WIP]add browse by network

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
the rather massive list in constants.py is due to tmdb not offering a name->id mapping for networks in their api so i had to scrape and save the id->name route

**Comment by evilpirate** [comment]
try dropping all ids that dont return 15-20 results or more, most of the ids i check return 0 to 1 results.
52|321|279 are for the australian abc, not the same as abc usa, try merging them with 18 and renaming that to ABC (AU) also bbc america 493 should probably be independent

**Comment by ghost** [comment]
is it possible to scrape the guidebox channels/television list from api.guidebox.com/apidocs#channels and replace their ids with the tmdb ids from constants.py? the channel names seem to match up? the list on guidebox has a nice sort order too.

**Comment by ghost** [comment]
primaeval seems to have solved this in a much better way with [(UK) TV Listings](http://forum.kodi.tv/showthread.php?tid=271858)

 closing this PR for now

**Comment by primaeval** [comment]
@midraal Feel free to use any/all/none of my addons/code in Meta or your addons if you like. You have done a great job with Meta.

**Pull request closed without merging**
