### PR TITLE
Live Tv support

### PR DESCRIPTION
**Pull request by ghost**
not done yet, opening up a PR so the code can be discussed

currently done:
- endpoint for tv guides to hook into
- "live" section for players
- text_to_number and number_to_text functions
- filter on channel for live players
- {name}, {basename},{extension} and {delay} parameters for player's live sections

example of new player parameters:
- channel: ITV2 +1
  - {name}: ITV2 +1
  - {basename}: ITV
  - {extension}: 2
  - {delay}: 1

known issues:
- text_to_number and number_to_text functions only go to 19
- regex for assigning parameters is probably not quite correct yet
- might need more parameters

### CODE REVIEW

**Comment by metate** [comment]
Excellent work midraal :+1: 

> text_to_number and number_to_text functions only go to 19

Maybe this can help https://github.com/ghewgill/text2num/blob/master/text2num.py

> regex for assigning parameters is probably not quite correct yet

Please provide examples to match against, it seems fine to me. Though you should probably add the re.UNICODE and re.IGNORECASE flags to re.compile.

It could be simpler to write players if we add an option to do all possible matching in the code itself. When a {channel} (or {clearchannel}?) pattern is specified in the player, change both the channel name and the label text to use numbers instead of text, separated with a space between adjacent words and without the trailing delay. What do you think?

**Comment by ghost** [comment]
i've tried doing it that way, but the problem is inconsistent naming in addons. some will use "1", others will use " 1" or "one"  or " one"

the regex seems to be holding up this time though, it's the 10th iteration or so of it i tried
i'll have a look at those flags, still rather new at doing regex

**Comment by ghost** [comment]
i think it's about done, could use some testing to catch any remaining bugs

**Comment by ghost** [comment]
rebased it for cleaner history

should be okay to merge

**Comment by metate** [comment]
Thanks midraal, will release it in a couple of days (got some unrelated fixes pending).

**Pull request merged**
