### PR TITLE
[WIP] further trakt integration

### PR DESCRIPTION
**Pull request by ghost**
currently done:
- trakt liked lists
- trakt my lists
- trakt recommendations

### CODE REVIEW

**Comment by metate** [comment]
@plugin.route('/authenticate_trakt') could conflict with the annotation in addon.py.

pagination code seems inefficient, should get a page parameter and only ask for the specific page, then in navigation add a page parameter like it's done for tmdb. You can keep the current code and I'll change it when you're done of course.

I was wondering if lists should be splitted by media type (tvshows,episodes, movies) but your choice seems like a good one.

Caching strategy needs re-thinking. I'll need to check if trakt supports http caching flags so we can use a cache but still reflect changes to trakt lists as soon as possible.

Again thanks for your massive contributions, it allows me to focus on a rewrite I'm working on (to improve the search and library modules). Cheers :)

**Comment by ghost** [comment]
hadn't seen the changed annotation, thanks for pointing it out

pagination right now doesn't seem to take  too long, altough i haven't tried with very large amounts of lists. i'll probably change it later on if it becomes a problem
 the 2-4 api calls for each item in a list to get the metadata are much worse, first time loading a list can take ages

i didn't split it up by type as some lists like https://trakt.tv/users/travisg100/lists/the-essential-x-files-episodes are viewing order suggestions with mixed types

i'm scratching my own itch with adding these things anyway. wouldn't be fair not to share it back upstream

**Comment by metate** [comment]
My suggestions:
1. Adding pagination to lists_trakt_show_list to show just 25 items (and a next>> item)
2. Have you tried getting extended info (full, images) in the list/(id)/items calls directly?
3. Do we really need to fetch tvshow for season metadata? I can tell that at least fetching the season for episode metadata isn't really needed.
4. Once we make sure we really make the minimal number of API calls we can use utils.executor to fetch multiple items simultaneously (like I do for fetching tvdb information)

**Comment by ghost** [comment]
just checked getting extended info and it works, that should limit the number of api calls considerably. strangely it's not noted in the api docs that it'll take that parameter

**Comment by ghost** [comment]
doin one call per list makes a huge difference, lists come up almost instantaneously now.
might have to tweak the labels/info a bit as its giving some weird labels atm

**Comment by ghost** [comment]
should be good to go after it gets some testing
still missing:
- Lists search
- Add to Trakt (Lists, My Movie Collection, My TV Collection)

Trakt on deck is the same as next episode, so it can be crossed of the list

not quite sure what to do about the labels on lists

**Comment by metate** [comment]
I'll test and adjust this weekend (hopefully). 

> not quite sure what to do about the labels on lists

What do you mean?

Edit: ignore the accidental closing of this PR.

**Comment by ghost** [comment]
the labels for episodes appear as {episodenumber} . {label} and seasons appear as {seasonnumber}X{label}
i think it has something to do with the info i'm setting. it also depends on which skin i'm using so it's most likely an issue with the skin itself.

**Comment by ghost** [comment]
i'm having a look at add to list as well

**Comment by midraal** [comment]
should be good to go. will add list search when its ready, as it's currently returning usernames but most are null. (maybe they are indexing?)

**Comment by ghost** [comment]
should be good to go. a lot of lists still return null for username so not all lists will be shown

**Comment by metate** [comment]
Merged, thanks :) Do you think it would be better to put all trakt stuff on its own section as you did initially? I think it becomes a bit messy, especially for users that don't use English (because trakt is English only).

**Comment by ghost** [comment]
might be better, but not sure

**Pull request merged**
