### PR TITLE
[WIP] Trakt integration

### PR DESCRIPTION
**Pull request by ghost**
adds basic trakt integration.

currently done:
- authentication
- collections
- playlists
- next episodes
- calendar (it looks atrocious, but it's more to see how to do it)
- add single item to library from collection/playlist
- add all to library from collection/playlist

known issues:
- no fananrt/posters
- adding all to library opens a dialog for each item when its a tv show listing (so lots of pressing enter needed)

### CODE REVIEW

**Comment by metate** [comment]
A few more things to be changed later (possibly by me):

Fix translatable text entries: 
    `from language import get_string as _` 
    Then use `_("text")` instead of `"text"`. 
    For example: `_("Add to library").`

Cache trakt results: 
    in trakt.py decorate functions that need to be cached with `@plugin.cached(TTL=CACHE_TTL, cache="trakt")`

Remove hardcoded URLs:
    use `plugin.url_for` where possible.

Add info labels and setting current Kodi view content type

**Comment by ghost** [comment]
still to do:
- add/remove from watchlist/collection
- custom lists (?)
- recommendations (?)

**Comment by ghost** [comment]
it seems to be in a usable state now, you can pull it in if you want.
could you replace CLIENT_ID and CLIENT_SECRET with your own tough?

**Comment by metate** [comment]
Sure. Will modify accordingly and add fanart and posters in the upcoming days

**Comment by metate** [comment]
@midraal 

Care to test latest master? I modified your code to fit into the existing movies and tv categories. If all works I'll take a look at custom lists and recommendations. Also, isn't add/remove from watchlist/collection part of script.trakt?

I'll hide the parts related to trakt library integration in the next release though. A unified library integration code is needed to keep the library in sync with multiple sources: adding from the popular category (tmdb) + watch list + collection should create no duplicates and automatically adjust the library when things are removed from source that was used to add them (at least for trakt sources).

**Comment by ghost** [comment]
looks good

add/remove from watchlist/collection isn't part of script.trakt afaik. i think it's only scrobbling and syncing watched/collected status

as far as the library integration code, it was already calling the movie/tv show library code, but a more unified approach might indeed be better as there were some changes i needed to make to the tv show code to actualy have it work adding multiple items without popping up tons of dialogs

**Pull request merged**
